### PR TITLE
Fix setSchema affecting older Statement objects

### LINKED ISSUE #58: Connection.setSchema() affects previously created Statements
https://github.com/openjdk/jdk/blob/ff52f2989fd60ec8251eaf76f4c4b78f10d3e048/src/java.sql/share/classes/java/sql/Connection.java#L1313-L1314

### PR DESCRIPTION
**Pull request by SeriyBg**
Fix #58

### CODE REVIEW

File: src/test/java/com/hazelcast/jdbc/JdbcConnectionIntegrationTest.java [hunk 1]
```diff
@@ -80,4 +81,14 @@ void shouldAutoCloseStatementWhenResultSetIsClosed() throws SQLException {
 
         assertThat(statement.isClosed()).isTrue();
     }
+
+    @Test
+    @Disabled("SQL module for now ignores the schema parameter from the API")
```
Comment (viliam-durina) [inline src/test/java/com/hazelcast/jdbc/JdbcConnectionIntegrationTest.java:86]: This comment isn't correct. You requested `WrongSchema`, but it's not ignored. The query doesn't contain any schema, so it tries to resolve the `person` table from `WrongSchema`. It's not there, so it proceeds with the default schemas, that is `public` and then `partitioned`. So it's correct that this test doesn't fail. 

You should do a test with Jet. Create a map `m` and also a mapping `m`. Both should have different columns or contentes. Without `setSchema`, the mapping should be used. If you set `partitioned` schema, the imap should be used directly, you can assert the returned columns.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

**Comment by devozerov** [comment]
LGTM except for Villiam's comment.

**Review by devozerov — APPROVED** [review]

**Comment by SeriyBg** [comment]
The PR is blocked by: https://github.com/hazelcast/hazelcast/issues/18428

**Review by Fly-Style — APPROVED** [review]

**Review by viliam-durina — APPROVED** [review]

**Review by hakanmemisoglu — APPROVED** [review]
